# Generated by Django 4.2.11 on 2026-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linux_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.TextField()),
                ('servergroup', models.TextField()),
                ('os_version', models.TextField()),
                ('uptime', models.TextField()),
            ],
        ),
    ]
