services:
  linux_inventory:
    image: wliari/linux_inventory:latest
    ports: 
    - 8000:8000

    environment:
      ansble_user: aritra
      ANSIBLE_HOST_KEY_CHECKING: False

    volumes:
    - /home/aritra/.ssh/:/root/.ssh/:rw
    - ./persistent/db.sqlite3:/app/db.sqlite3
  
